pipeline {
    agent any

    environment {
        IMAGE_NAME = 'samyogg/java-cicd-pipeline'
        IMAGE_TAG  = "${BUILD_NUMBER}"
        REGISTRY_CREDENTIALS = 'dockerhub-samyogg'
    }

    stages {

        stage('Build & Test') {
            steps {
                sh 'mvn clean package'
            }
        }

        stage('Build & Push Docker Image') {
            steps {
                script {
                    def img = docker.build("${IMAGE_NAME}:${IMAGE_TAG}")
                    docker.withRegistry('', REGISTRY_CREDENTIALS) {
                        img.push()
                        img.push('latest')
                    }
                }
            }
        }

        stage('Update Kubernetes Deployment') {
            steps {
                sh """
                    git config user.email "samyog.ghimire25@gmail.com"
                    git config user.name "SamyogGhimire"

                    sed -i 's|image: .*|image: ${IMAGE_NAME}:${IMAGE_TAG}|g' \
                        ../k8s-app-manifests/deployment.yaml

                    git add ../k8s-app-manifests/deployment.yaml
                    git commit -m "Update image to ${IMAGE_NAME}:${IMAGE_TAG}"
                    git push https://github.com/SamyogGhimire/CICD-Pipeline.git
                """
            }
        }
    }
}
