pipeline {
  agent any

  environment {
    IMAGE_NAME = 'samyogg/java-cicd-pipeline'
    REGISTRY_CREDENTIALS = 'dockerhub-samyogg'
    GIT_CREDENTIALS_ID = 'Github latest token'
    MANIFEST_FILE = 'k8s-app-manifests/deployment.yaml'
  }

  stages {

    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Build & Test') {
      steps {
        dir('spring-boot-app') {
          sh 'mvn clean package -DskipTests'
        }
      }
    }

    stage('Build Docker Image') {
      steps {
        script {
          IMAGE_TAG = "${BUILD_NUMBER}"
          sh "docker build -t $IMAGE_NAME:$IMAGE_TAG spring-boot-app"
        }
      }
    }

    stage('Push Docker Image') {
      steps {
        withCredentials([usernamePassword(
          credentialsId: REGISTRY_CREDENTIALS,
          usernameVariable: 'DOCKER_USER',
          passwordVariable: 'DOCKER_PASS'
        )]) {
          sh """
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker push $IMAGE_NAME:${BUILD_NUMBER}
          """
        }
      }
    }

    stage('Update Kubernetes Deployment') {
      steps {
        sh """
          sed -i 's|image: .*|image: $IMAGE_NAME:${BUILD_NUMBER}|' $MANIFEST_FILE
        """
      }
    }

    stage('Commit & Push Manifest') {
      steps {
        withCredentials([usernamePassword(
          credentialsId: GIT_CREDENTIALS_ID,
          usernameVariable: 'GIT_USER',
          passwordVariable: 'GIT_PASS'
        )]) {
          sh """
            git config user.email "jenkins@ci.local"
            git config user.name "jenkins"
            git add $MANIFEST_FILE
            git commit -m "Update image to $IMAGE_NAME:${BUILD_NUMBER}"
            git push https://$GIT_USER:$GIT_PASS@github.com/SamyogGhimire/CICD-Pipeline.git HEAD:main
          """
        }
      }
    }
  }
}
